# -*- coding: utf-8 -*-
"""Trabalho final modulo 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cZgUGG3K9Z3OtJ8p_paSO--GBzw5dxOb
"""

#import
import pandas as pd
import numpy as np

df = pd.read_csv("bike-sharing.csv")

df.info()

#a. Qual o tamanho do data frame?
df.size

#b. Qual a média da coluna windspeed?
df['windspeed'].mean()

#c. Qual a média da coluna temp?
df['temp'].mean()

#d. Quantos registros existem para o ano de 2011?
df.head(5)
#df = df.set_index('datetime')
df['datetime'] = pd.to_datetime(df['datetime'])
df['year'] = df['datetime'].dt.year
df[df['year'] == 2011]

#e. Quantos registros existem para o ano de 2012?
df[df['year'] == 2012]

#f. Quantas locações de bicicletas foram efetuadas em 2011?
loc = df[df['year'] == 2011]['total_count'].sum()
loc

#g. Quantas locações de bicicletas foram efetuadas em 2012?
loc2012 = df[df['year'] == 2012]['total_count'].sum()
loc2012

#h. Qual estação do ano contém a maior média de locações de bicicletas?
df.groupby('season')['total_count'].mean().sort_values()

#i. Qual estação do ano contém a menor média de locações de bicicletas?
df.groupby('season')['total_count'].mean().sort_values()

#j. Qual horário do dia contém a maior média de locações de bicicletas?
df.groupby('hour')['total_count'].mean().sort_values(ascending = False)

#k. Qual horário do dia contém a menor média de locações de bicicletas?
df.groupby('hour')['total_count'].mean().sort_values()

#l. Que dia da semana contém a maior média de locações de bicicletas?
df.groupby('weekday')['total_count'].mean().sort_values(ascending = False)

#m. Que dia da semana contém a menor média de locações de bicicletas?
df.groupby('weekday')['total_count'].mean().sort_values()

#n. Às quartas-feiras (weekday = 3), qual o horário do dia que contém a maior média de locações de bicicletas?
cond = df[df['weekday'] == 3]
cond.groupby('hour')['total_count'].mean().sort_values(ascending = False)

#o. Aos sábados (weekday = 6), qual o horário do dia que contém a maior média de locações de bicicletas?
cond = df[df['weekday'] == 6]
cond.groupby('hour')['total_count'].mean().sort_values(ascending = False)